### PR TITLE
Refactor `TYPEOF` to enum-style

### PR DESCRIPTION
**Pull request by CGMossa**
Replacing #210, #211 and #207. The git churn was getting out of hand. 

This PR unifies `TYPEOF` output to a `SEXTYPE`, where now, `SEXPTYPE` is an `enum`.
Furthermore
* Update bindings
* Update `test.yml`'s download-action (download-artifact) to use latest version

### CODE REVIEW

**Comment by yutannihilation** [comment]
Shouldn't this be `#[non_exhaustive]`?

**Comment by CGMossa** [comment]
> Shouldn't this be `#[non_exhaustive]`?

I never know. I can make it so 😂

**Comment by CGMossa** [comment]
> Shouldn't this be `#[non_exhaustive]`?

Done! Feel free to review this PR, as that would be very good for me 😆

**Review by Ilia-Kosenkov — APPROVED** [review]
LGTM, makes API much easier to understand & handle!

**Comment by CGMossa** [comment]
Yes! And I'm going to do it _very_ soon.

**Comment by yutannihilation** [comment]
Great.

**Pull request merged**
