### PR TITLE
Update bindings

### PR DESCRIPTION
**Pull request by yutannihilation**
to reflect these changes:

* https://github.com/extendr/libR-sys/pull/160
* https://github.com/extendr/libR-sys/pull/165

### CODE REVIEW

**Comment by Ilia-Kosenkov** [comment]
Do you know why it switched from c_uint to i32?

**Comment by yutannihilation** [comment]
Because of this change. https://github.com/extendr/libR-sys/pull/160

**Comment by CGMossa** [comment]
Maybe due to this https://github.com/extendr/libR-sys/blob/master/build.rs#L460

**Review by Ilia-Kosenkov — APPROVED** [review]

**Comment by yutannihilation** [comment]
Thanks for approving!

**Pull request merged**
