### PR TITLE
[WIP] Make winapi optional

### LINKED ISSUE #107: Can we make winapi optional?
`winapi` is needed because the output of R was not UTF-8 on Windows, and that was a problem (https://github.com/extendr/libR-sys/pull/18#issuecomment-741873561). But, it seems winapi is too heavy to include only for this purpose. I think

* The default encoding of R >= 4.2 is UTF-8 on Windows (but the default of the OS might not, so I'm not sure if it's really safe to assume that `rout` is UTF-8)
* But, at least we can set `LIBRSYS_R_VERSION` so that we don't need to communicate the output of `R`

```
$ du -sh vendor/* | grep M
5.5M    vendor/libR-sys
3.7M    vendor/libc
2.1M    vendor/syn
7.6M    vendor/winapi
53M     vendor/winapi-i686-pc-windows-gnu
55M     vendor/winapi-x86_64-pc-windows-gnu
```

### PR DESCRIPTION
**Pull request by yutannihilation**
Fix #107

### CODE REVIEW

**Comment by Ilia-Kosenkov** [comment]
Can we merge this?

**Comment by yutannihilation** [comment]
While I opened this, I hope we don't need to merge this. Adding this option increases the cases that we need to test.

**Comment by Ilia-Kosenkov** [comment]
Ok, I will open a PR with my version of these changes. Let's see how it works.

**Comment by yutannihilation** [comment]
Fixed by #109

**Pull request closed without merging**
