### PR TITLE
Add function signature attributes

### PR DESCRIPTION
**Pull request by CGMossa**
There are various updates that I wanted to put together, mainly:

* `enable-function-attribute-detection` that should address the `-> !`, issue, see <https://ferrous-systems.com/blog/bindgen/>.
* `cargo doc` warnings
* updating `bindgen` to ensure that we follow the progress there

I've tried to do more with bindings, and I've semi-successful MVPs, but they are not ready for `libR-sys`.

### CODE REVIEW

**Comment by yutannihilation** [comment]
Could you separate each change to its own PR?

**Comment by CGMossa** [comment]
Why? They are very minute.

I see now I accidentally committed something unnecessary...

**Comment by yutannihilation** [comment]
Because we cannot track which one of your changes would affect what part of the bindings.

**Comment by CGMossa** [comment]
Closing this in favour of #177

**Pull request closed without merging**
