### PR TITLE
Address the change of Rcomplex in R 4.3? 4.4?

### PR DESCRIPTION
**Pull request by yutannihilation**
`build.rs` didn't expect `Union` will be used in the API, so this pull request just adds it.

Note that, while the fix is very simple, I think extendr will no longer compile because it assumes `Rcomplex` is a struct.

### CODE REVIEW

**Review by Ilia-Kosenkov — APPROVED** [review]

**Comment by kevinushey** [comment]
Can I ask, are there plans to push a new release of `libR-sys` to crates.io with this change?

**Comment by kevinushey** [comment]
As I understand it, the current release of `libR-sys` on crates.io cannot be used with R 4.3? We could install an older version of R, but that gets a bit hairy (especially on GitHub Actions where the version of R installed by default is R 4.3)

**Comment by CGMossa** [comment]
You can link to the github version directly from your rust project.

**Comment by yutannihilation** [comment]
@kevinushey 
Sorry for my laziness. Yes, I was thinking I should publish a new version.

Just to be clear, libR-sys ended up with overwriting the `Rcomplex` definition to the old one before R 4.2, so you should not have any problem if you are using the precomputed bindings: https://github.com/extendr/libR-sys/pull/156/files#diff-deb55fa2ae44b6a308358532a2ee3b866bd5866626cad96c31108d2f13d2f9d3

But, if you generate the bindings by yourself, you'll definitely need this change.

**Comment by yutannihilation** [comment]
@kevinushey
Do you see any actual problem related to Rcomplex because of not releasing the new version? I expect there's nothing, but If there's any, it means I might not understand the problem correctly. So, I'm curious.

**Comment by kevinushey** [comment]
Sorry, I missed your message! We are all set on our side now, though -- thank you :-)

**Comment by yutannihilation** [comment]
Thanks for sharing!

**Pull request merged**
