### PR TITLE
Merge extern blocks

### PR DESCRIPTION
**Pull request by CGMossa**
This reduces the bindings by 2k LOC.

- [ ] depends on #186

### CODE REVIEW

**Comment by yutannihilation** [comment]
Looks good, but I'm curious why this requires the newer version of bindgen. It seems `merge_extern_blocks()` exists in more earlier versions. Do you find any problem?

**Comment by CGMossa** [comment]
Oh! Right the dependence is because I was trying to show what PR to review first and approve first.

Because then you get a nice merging between the generated bindings.

**Comment by yutannihilation** [comment]
Ah, I see, thanks. Then, I'm approving both now.

**Review by yutannihilation — APPROVED** [review]

**Pull request merged**
