### PR TITLE
Add /bindings command

### LINKED ISSUE #129: Add a command to generate bindings on a pull request
Like this one. https://github.com/r-lib/actions/blob/v2-branch/examples/pr-commands.yaml

### PR DESCRIPTION
**Pull request by yutannihilation**
Close #129

This pull request allows us to generate bindings on a pull request by just commenting `/bindings`. But, this works only after this gets merged into the master branch, so it's a bit difficult to test this.

### CODE REVIEW

**Comment by yutannihilation** [comment]
Hmm, it seems it's a bit difficult to test this...

**Review by CGMossa — APPROVED** [review]
LGTM

**Comment by yutannihilation** [comment]
Thanks!

**Comment by yutannihilation** [comment]
Hmm, sorry, it seems I failed to implement this properly. Will fix later...

**Pull request merged**
