### PR TITLE
Follow standard for opaque types in case of `SEXPREC`

### PR DESCRIPTION
**Pull request by CGMossa**
Since `SEXPREC` is an opaque type, that R doesn't want us to construct, or know anything about, or even
want us to make assumptions about. But, currently, we do! We assume that it is Send, Sync and Pin.
(see `cargo doc` pictures below).

I've made an issue about this https://github.com/rust-lang/rust-bindgen/issues/2685, because 
bindgen has an `opaque_type`, mechanism, and it is not producing a version with the 
`!Send,!Sync,!Pin`. But the https://stackoverflow.com/questions/38315383/whats-the-rust-idiom-to-define-a-field-pointing-to-a-c-opaque-pointer, and https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs, 
explains how to do this:

Going from

```rs
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct SEXPREC {
    _unused: [u8; 0],
}
```

to 

```rs
#[repr(C)]
pub struct SEXPREC {
    _data: [u8; 0],
    _marker:
        core::marker::PhantomData<(*mut u8, core::marker::PhantomPinned)>,
}
```

Results of this code can only be read-off `cargo doc`, so see the images below:

Currently:
image

Now:
image

Depends on:

- [ ] #208

### CODE REVIEW

**Comment by CGMossa** [comment]
An example of the issues mentioned in #204 is here. What do I do now to showcase a PR? It breaks CI, so no-one will look. Even if the resulting bindings would work, if they were the ones saved and used in this PR.

**Comment by CGMossa** [comment]
@yutannihilation

**Comment by CGMossa** [comment]
@yutannihilation, since this works now, I'd like your thoughts on this.

**Comment by yutannihilation** [comment]
Looks great, but let me confirm. In my understanding, `SEXPREC` is not a type of opaque type that needs to be exposed to the user because the API interface always uses `SEXP`, not `SEXPREC` directly. Does it make sense to block both `SEXP` and `SEXPREC` and manually define as below?

``` rust
pub type SEXP = *mut ::std::os::raw::c_void;
```

**Comment by CGMossa** [comment]
I'm not sure. I don't think we should make `SEXP` a `void*`.

I believe Opaque Type atleast implies that it is a type we don't know how to construct, and that we are not allowed to construct. In Rust, that's accomplished with a private field, thus making it impossible to construct the type **outside of the defining module**.

I tried to do this:
image

But then `SEXP` becomes
image

Which is, in my opinion, the wrong definition. Because we can construct this.

I don't think we should blindly trust what `bindgen` produces. It is actively being developed.

I'm not sure if this PR has any impact. I think we should maybe include this PR, just for **correctness**.
I hope someone explains if this has an impact. Atleast this PR follows rust-documentation. Otherwise I don't know at all...

**Comment by yutannihilation** [comment]
After reading [the Rustonomicon](https://doc.rust-lang.org/nomicon/ffi.html#representing-opaque-structs) again, I found my understanding about the opaque type was wrong, sorry. It seems you are right.

In this case, I'm still wondering if it's any better to expose the "type-safe" `SEXPREC` than to hide everything behind `c_void` because, unlike the Rustonomicon's example, the users always have to use `SEXP`. Anyway, except for this nitpicky point, I don't see any problem so I'm approving.

(JFYI, I decided to use `*mut c_void` in [my smaller alternative to libR-sys](https://github.com/yutannihilation/savvy/blob/703fa8c2532f523dd6ff8672482231b70e421f93/rlang-ffi-lite/src/lib.rs#L14), so I'll share if I find some difference that might matter)

**Review by yutannihilation — APPROVED** [review]

**Comment by CGMossa** [comment]
Ok. Thanks for approval.
However, I'll wait until the fix for ci has been reviewed, and if someone on the bindgen part, or another rust ffi expert says something.

**Comment by CGMossa** [comment]
This is the wrong approach. SEXPREC should be regarded as `c_void`. I'll put another PR, once I figure out how to make bindgen produce what I want..

**Pull request closed without merging**
