### PR TITLE
Use allowlist to keep the exports minimal

### PR DESCRIPTION
**Pull request by yutannihilation**
See https://github.com/extendr/libR-sys/issues/95#issuecomment-1037084923

Currently, libR-sys exports all symbols wildly, including those from the C standard library. I think we should keep the exports minimal to avoid confusion. This pull request tries to create a proper allowlist. The basic idea is to extract and parse the include files by ourselves first and construct an allowlist because there seems not measure to stop bindgen to parse the C standard library.

### CODE REVIEW

**Comment by yutannihilation** [comment]
@Ilia-Kosenkov @andy-thomason 
This isn't very high priority and probably is difficult to understand, but I'd like to hear your thoughts on this. I think this is a necessary move not only to prevent such confusions as https://github.com/extendr/libR-sys/issues/95, but also to reduce the code size. Note that I've been using this branch for my CRAN package without any problem, so I believe this is ready to merge basically.

**Comment by yutannihilation** [comment]
@Ilia-Kosenkov 
May I merge this?

**Comment by Ilia-Kosenkov** [comment]
Looks good, but let me restart CI since the last run was ~2 weeks ago -- to be on the safe side.

**Review by Ilia-Kosenkov — APPROVED** [review]
LGTM, thanks & sorry for delay

**Comment by yutannihilation** [comment]
No worries. Thanks for reviewing!

**Pull request merged**
